name: Build

on:
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [22, 24]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: TypeScript typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build
